# golangci-lint configuration for LauraDB
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - data
    - coverage
  skip-files:
    - ".*_test\\.go$"  # Skip test files for some linters

linters:
  enable:
    # Error detection
    - errcheck        # Check for unchecked errors
    - govet          # Vet examines Go source code and reports suspicious constructs
    - staticcheck    # Advanced static analysis
    - typecheck      # Type check code

    # Code quality
    - gofmt          # Check code formatting
    - goimports      # Check import formatting
    - ineffassign    # Detect ineffectual assignments
    - misspell       # Find commonly misspelled English words
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Report unused function parameters
    - unused         # Find unused constants, variables, functions and types

    # Style
    - gocyclo        # Detect cyclomatic complexity
    - goconst        # Find repeated strings that could be replaced by constants
    - godot          # Check that comments end in periods
    - gosimple       # Suggest code simplifications

    # Performance
    - prealloc       # Find slice declarations that could be preallocated

    # Best practices
    - revive         # Fast, configurable, extensible, flexible linter
    - exportloopref  # Check for pointers to enclosing loop variables
    - nilerr         # Find code that returns nil even if check error

  disable:
    - deadcode       # Deprecated
    - varcheck       # Deprecated
    - structcheck    # Deprecated
    - golint         # Deprecated (use revive instead)
    - interfacer     # Deprecated
    - scopelint      # Deprecated (use exportloopref)
    - maligned       # Deprecated

linters-settings:
  gocyclo:
    min-complexity: 15  # Allow moderate complexity

  revive:
    rules:
      - name: exported
        disabled: true  # Don't require comments on all exported items
      - name: package-comments
        disabled: true  # Don't require package comments

  govet:
    check-shadowing: true
    enable-all: true

  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow _ = err assignments

  gofmt:
    simplify: true

  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude known false positives
    - linters:
        - staticcheck
      text: "SA1019:"  # Ignore deprecation warnings for now

  max-issues-per-linter: 0
  max-same-issues: 0

  # Show all issues
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
