// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/cluster/proto/cluster.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeRole int32

const (
	NodeRole_UNKNOWN       NodeRole = 0
	NodeRole_PRIMARY       NodeRole = 1
	NodeRole_SECONDARY     NodeRole = 2
	NodeRole_ARBITER       NodeRole = 3
	NodeRole_SHARD         NodeRole = 4
	NodeRole_CONFIG_SERVER NodeRole = 5
	NodeRole_ROUTER        NodeRole = 6
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "UNKNOWN",
		1: "PRIMARY",
		2: "SECONDARY",
		3: "ARBITER",
		4: "SHARD",
		5: "CONFIG_SERVER",
		6: "ROUTER",
	}
	NodeRole_value = map[string]int32{
		"UNKNOWN":       0,
		"PRIMARY":       1,
		"SECONDARY":     2,
		"ARBITER":       3,
		"SHARD":         4,
		"CONFIG_SERVER": 5,
		"ROUTER":        6,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_cluster_proto_cluster_proto_enumTypes[0].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_pkg_cluster_proto_cluster_proto_enumTypes[0]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{0}
}

// Node represents a LauraDB node in the cluster
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                               // Unique node identifier
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`                                                                           // Hostname or IP address
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                                                                          // Port number
	Role          NodeRole               `protobuf:"varint,4,opt,name=role,proto3,enum=lauradb.cluster.NodeRole" json:"role,omitempty"`                                            // Current role in the cluster
	Priority      int64                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                                                                  // Election priority (higher = more likely to become primary)
	Tags          map[string]string      `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom tags for targeting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Node) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Node) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_UNKNOWN
}

func (x *Node) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Node) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// NodeRegistration is sent when a node joins the cluster
type NodeRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	SeedNodes     []string               `protobuf:"bytes,2,rep,name=seed_nodes,json=seedNodes,proto3" json:"seed_nodes,omitempty"` // Known nodes to connect to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRegistrationRequest) Reset() {
	*x = NodeRegistrationRequest{}
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegistrationRequest) ProtoMessage() {}

func (x *NodeRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegistrationRequest.ProtoReflect.Descriptor instead.
func (*NodeRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *NodeRegistrationRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeRegistrationRequest) GetSeedNodes() []string {
	if x != nil {
		return x.SeedNodes
	}
	return nil
}

type NodeRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ClusterNodes  []*Node                `protobuf:"bytes,3,rep,name=cluster_nodes,json=clusterNodes,proto3" json:"cluster_nodes,omitempty"` // Current cluster members
	Topology      *ClusterTopology       `protobuf:"bytes,4,opt,name=topology,proto3" json:"topology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRegistrationResponse) Reset() {
	*x = NodeRegistrationResponse{}
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegistrationResponse) ProtoMessage() {}

func (x *NodeRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegistrationResponse.ProtoReflect.Descriptor instead.
func (*NodeRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *NodeRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NodeRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NodeRegistrationResponse) GetClusterNodes() []*Node {
	if x != nil {
		return x.ClusterNodes
	}
	return nil
}

func (x *NodeRegistrationResponse) GetTopology() *ClusterTopology {
	if x != nil {
		return x.Topology
	}
	return nil
}

// NodeDeregistration is sent when a node gracefully leaves
type NodeDeregistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDeregistrationRequest) Reset() {
	*x = NodeDeregistrationRequest{}
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDeregistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDeregistrationRequest) ProtoMessage() {}

func (x *NodeDeregistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDeregistrationRequest.ProtoReflect.Descriptor instead.
func (*NodeDeregistrationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *NodeDeregistrationRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeDeregistrationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type NodeDeregistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDeregistrationResponse) Reset() {
	*x = NodeDeregistrationResponse{}
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDeregistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDeregistrationResponse) ProtoMessage() {}

func (x *NodeDeregistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDeregistrationResponse.ProtoReflect.Descriptor instead.
func (*NodeDeregistrationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *NodeDeregistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NodeDeregistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ClusterTopology represents the current cluster state
type ClusterTopology struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // Incremented on every topology change
	Nodes         []*Node                `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	PrimaryId     string                 `protobuf:"bytes,3,opt,name=primary_id,json=primaryId,proto3" json:"primary_id,omitempty"`
	ReplicaSets   []*ReplicaSet          `protobuf:"bytes,4,rep,name=replica_sets,json=replicaSets,proto3" json:"replica_sets,omitempty"`
	Shards        []*ShardInfo           `protobuf:"bytes,5,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterTopology) Reset() {
	*x = ClusterTopology{}
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterTopology) ProtoMessage() {}

func (x *ClusterTopology) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterTopology.ProtoReflect.Descriptor instead.
func (*ClusterTopology) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *ClusterTopology) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClusterTopology) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ClusterTopology) GetPrimaryId() string {
	if x != nil {
		return x.PrimaryId
	}
	return ""
}

func (x *ClusterTopology) GetReplicaSets() []*ReplicaSet {
	if x != nil {
		return x.ReplicaSets
	}
	return nil
}

func (x *ClusterTopology) GetShards() []*ShardInfo {
	if x != nil {
		return x.Shards
	}
	return nil
}

type ReplicaSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeIds       []string               `protobuf:"bytes,2,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	PrimaryId     string                 `protobuf:"bytes,3,opt,name=primary_id,json=primaryId,proto3" json:"primary_id,omitempty"`
	Term          int64                  `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"` // Raft-style term for leader election
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaSet) Reset() {
	*x = ReplicaSet{}
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaSet) ProtoMessage() {}

func (x *ReplicaSet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaSet.ProtoReflect.Descriptor instead.
func (*ReplicaSet) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *ReplicaSet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReplicaSet) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *ReplicaSet) GetPrimaryId() string {
	if x != nil {
		return x.PrimaryId
	}
	return ""
}

func (x *ReplicaSet) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type ShardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Chunks        []*ChunkRange          `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardInfo) Reset() {
	*x = ShardInfo{}
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardInfo) ProtoMessage() {}

func (x *ShardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardInfo.ProtoReflect.Descriptor instead.
func (*ShardInfo) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *ShardInfo) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ShardInfo) GetChunks() []*ChunkRange {
	if x != nil {
		return x.Chunks
	}
	return nil
}

// Heartbeat messages for health monitoring
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        *NodeStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() *NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Topology      *ClusterTopology       `protobuf:"bytes,3,opt,name=topology,proto3" json:"topology,omitempty"` // Updated topology if changed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *HeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatResponse) GetTopology() *ClusterTopology {
	if x != nil {
		return x.Topology
	}
	return nil
}

type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          NodeRole               `protobuf:"varint,1,opt,name=role,proto3,enum=lauradb.cluster.NodeRole" json:"role,omitempty"`
	LastOplogId   int64                  `protobuf:"varint,2,opt,name=last_oplog_id,json=lastOplogId,proto3" json:"last_oplog_id,omitempty"` // For replication lag monitoring
	Resources     *ResourceStats         `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *NodeStatus) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_UNKNOWN
}

func (x *NodeStatus) GetLastOplogId() int64 {
	if x != nil {
		return x.LastOplogId
	}
	return 0
}

func (x *NodeStatus) GetResources() *ResourceStats {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ResourceStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent     float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes    int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	DiskBytesUsed  int64                  `protobuf:"varint,3,opt,name=disk_bytes_used,json=diskBytesUsed,proto3" json:"disk_bytes_used,omitempty"`
	DiskBytesTotal int64                  `protobuf:"varint,4,opt,name=disk_bytes_total,json=diskBytesTotal,proto3" json:"disk_bytes_total,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceStats) Reset() {
	*x = ResourceStats{}
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceStats) ProtoMessage() {}

func (x *ResourceStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceStats.ProtoReflect.Descriptor instead.
func (*ResourceStats) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *ResourceStats) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceStats) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceStats) GetDiskBytesUsed() int64 {
	if x != nil {
		return x.DiskBytesUsed
	}
	return 0
}

func (x *ResourceStats) GetDiskBytesTotal() int64 {
	if x != nil {
		return x.DiskBytesTotal
	}
	return 0
}

type GetTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinVersion    int64                  `protobuf:"varint,1,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"` // Return only if topology version > this
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyRequest) Reset() {
	*x = GetTopologyRequest{}
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyRequest) ProtoMessage() {}

func (x *GetTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetTopologyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *GetTopologyRequest) GetMinVersion() int64 {
	if x != nil {
		return x.MinVersion
	}
	return 0
}

var File_pkg_cluster_proto_cluster_proto protoreflect.FileDescriptor

const file_pkg_cluster_proto_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/cluster/proto/cluster.proto\x12\x0flauradb.cluster\x1a\x1epkg/cluster/proto/common.proto\"\xf7\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12-\n" +
	"\x04role\x18\x04 \x01(\x0e2\x19.lauradb.cluster.NodeRoleR\x04role\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x03R\bpriority\x123\n" +
	"\x04tags\x18\x06 \x03(\v2\x1f.lauradb.cluster.Node.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\x17NodeRegistrationRequest\x12)\n" +
	"\x04node\x18\x01 \x01(\v2\x15.lauradb.cluster.NodeR\x04node\x12\x1d\n" +
	"\n" +
	"seed_nodes\x18\x02 \x03(\tR\tseedNodes\"\xc8\x01\n" +
	"\x18NodeRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\rcluster_nodes\x18\x03 \x03(\v2\x15.lauradb.cluster.NodeR\fclusterNodes\x12<\n" +
	"\btopology\x18\x04 \x01(\v2 .lauradb.cluster.ClusterTopologyR\btopology\"L\n" +
	"\x19NodeDeregistrationRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"P\n" +
	"\x1aNodeDeregistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xeb\x01\n" +
	"\x0fClusterTopology\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12+\n" +
	"\x05nodes\x18\x02 \x03(\v2\x15.lauradb.cluster.NodeR\x05nodes\x12\x1d\n" +
	"\n" +
	"primary_id\x18\x03 \x01(\tR\tprimaryId\x12>\n" +
	"\freplica_sets\x18\x04 \x03(\v2\x1b.lauradb.cluster.ReplicaSetR\vreplicaSets\x122\n" +
	"\x06shards\x18\x05 \x03(\v2\x1a.lauradb.cluster.ShardInfoR\x06shards\"j\n" +
	"\n" +
	"ReplicaSet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnode_ids\x18\x02 \x03(\tR\anodeIds\x12\x1d\n" +
	"\n" +
	"primary_id\x18\x03 \x01(\tR\tprimaryId\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x03R\x04term\"t\n" +
	"\tShardInfo\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x123\n" +
	"\x06chunks\x18\x03 \x03(\v2\x1b.lauradb.cluster.ChunkRangeR\x06chunks\"~\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x123\n" +
	"\x06status\x18\x03 \x01(\v2\x1b.lauradb.cluster.NodeStatusR\x06status\"\x81\x01\n" +
	"\x11HeartbeatResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12<\n" +
	"\btopology\x18\x03 \x01(\v2 .lauradb.cluster.ClusterTopologyR\btopology\"\x9d\x01\n" +
	"\n" +
	"NodeStatus\x12-\n" +
	"\x04role\x18\x01 \x01(\x0e2\x19.lauradb.cluster.NodeRoleR\x04role\x12\"\n" +
	"\rlast_oplog_id\x18\x02 \x01(\x03R\vlastOplogId\x12<\n" +
	"\tresources\x18\x03 \x01(\v2\x1e.lauradb.cluster.ResourceStatsR\tresources\"\xa5\x01\n" +
	"\rResourceStats\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12&\n" +
	"\x0fdisk_bytes_used\x18\x03 \x01(\x03R\rdiskBytesUsed\x12(\n" +
	"\x10disk_bytes_total\x18\x04 \x01(\x03R\x0ediskBytesTotal\"5\n" +
	"\x12GetTopologyRequest\x12\x1f\n" +
	"\vmin_version\x18\x01 \x01(\x03R\n" +
	"minVersion*j\n" +
	"\bNodeRole\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPRIMARY\x10\x01\x12\r\n" +
	"\tSECONDARY\x10\x02\x12\v\n" +
	"\aARBITER\x10\x03\x12\t\n" +
	"\x05SHARD\x10\x04\x12\x11\n" +
	"\rCONFIG_SERVER\x10\x05\x12\n" +
	"\n" +
	"\x06ROUTER\x10\x062\x8a\x03\n" +
	"\x0eClusterService\x12c\n" +
	"\fRegisterNode\x12(.lauradb.cluster.NodeRegistrationRequest\x1a).lauradb.cluster.NodeRegistrationResponse\x12i\n" +
	"\x0eDeregisterNode\x12*.lauradb.cluster.NodeDeregistrationRequest\x1a+.lauradb.cluster.NodeDeregistrationResponse\x12R\n" +
	"\tHeartbeat\x12!.lauradb.cluster.HeartbeatRequest\x1a\".lauradb.cluster.HeartbeatResponse\x12T\n" +
	"\vGetTopology\x12#.lauradb.cluster.GetTopologyRequest\x1a .lauradb.cluster.ClusterTopologyB1Z/github.com/mnohosten/laura-db/pkg/cluster/protob\x06proto3"

var (
	file_pkg_cluster_proto_cluster_proto_rawDescOnce sync.Once
	file_pkg_cluster_proto_cluster_proto_rawDescData []byte
)

func file_pkg_cluster_proto_cluster_proto_rawDescGZIP() []byte {
	file_pkg_cluster_proto_cluster_proto_rawDescOnce.Do(func() {
		file_pkg_cluster_proto_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_cluster_proto_cluster_proto_rawDesc), len(file_pkg_cluster_proto_cluster_proto_rawDesc)))
	})
	return file_pkg_cluster_proto_cluster_proto_rawDescData
}

var file_pkg_cluster_proto_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_cluster_proto_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_cluster_proto_cluster_proto_goTypes = []any{
	(NodeRole)(0),                      // 0: lauradb.cluster.NodeRole
	(*Node)(nil),                       // 1: lauradb.cluster.Node
	(*NodeRegistrationRequest)(nil),    // 2: lauradb.cluster.NodeRegistrationRequest
	(*NodeRegistrationResponse)(nil),   // 3: lauradb.cluster.NodeRegistrationResponse
	(*NodeDeregistrationRequest)(nil),  // 4: lauradb.cluster.NodeDeregistrationRequest
	(*NodeDeregistrationResponse)(nil), // 5: lauradb.cluster.NodeDeregistrationResponse
	(*ClusterTopology)(nil),            // 6: lauradb.cluster.ClusterTopology
	(*ReplicaSet)(nil),                 // 7: lauradb.cluster.ReplicaSet
	(*ShardInfo)(nil),                  // 8: lauradb.cluster.ShardInfo
	(*HeartbeatRequest)(nil),           // 9: lauradb.cluster.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 10: lauradb.cluster.HeartbeatResponse
	(*NodeStatus)(nil),                 // 11: lauradb.cluster.NodeStatus
	(*ResourceStats)(nil),              // 12: lauradb.cluster.ResourceStats
	(*GetTopologyRequest)(nil),         // 13: lauradb.cluster.GetTopologyRequest
	nil,                                // 14: lauradb.cluster.Node.TagsEntry
	(*ChunkRange)(nil),                 // 15: lauradb.cluster.ChunkRange
}
var file_pkg_cluster_proto_cluster_proto_depIdxs = []int32{
	0,  // 0: lauradb.cluster.Node.role:type_name -> lauradb.cluster.NodeRole
	14, // 1: lauradb.cluster.Node.tags:type_name -> lauradb.cluster.Node.TagsEntry
	1,  // 2: lauradb.cluster.NodeRegistrationRequest.node:type_name -> lauradb.cluster.Node
	1,  // 3: lauradb.cluster.NodeRegistrationResponse.cluster_nodes:type_name -> lauradb.cluster.Node
	6,  // 4: lauradb.cluster.NodeRegistrationResponse.topology:type_name -> lauradb.cluster.ClusterTopology
	1,  // 5: lauradb.cluster.ClusterTopology.nodes:type_name -> lauradb.cluster.Node
	7,  // 6: lauradb.cluster.ClusterTopology.replica_sets:type_name -> lauradb.cluster.ReplicaSet
	8,  // 7: lauradb.cluster.ClusterTopology.shards:type_name -> lauradb.cluster.ShardInfo
	15, // 8: lauradb.cluster.ShardInfo.chunks:type_name -> lauradb.cluster.ChunkRange
	11, // 9: lauradb.cluster.HeartbeatRequest.status:type_name -> lauradb.cluster.NodeStatus
	6,  // 10: lauradb.cluster.HeartbeatResponse.topology:type_name -> lauradb.cluster.ClusterTopology
	0,  // 11: lauradb.cluster.NodeStatus.role:type_name -> lauradb.cluster.NodeRole
	12, // 12: lauradb.cluster.NodeStatus.resources:type_name -> lauradb.cluster.ResourceStats
	2,  // 13: lauradb.cluster.ClusterService.RegisterNode:input_type -> lauradb.cluster.NodeRegistrationRequest
	4,  // 14: lauradb.cluster.ClusterService.DeregisterNode:input_type -> lauradb.cluster.NodeDeregistrationRequest
	9,  // 15: lauradb.cluster.ClusterService.Heartbeat:input_type -> lauradb.cluster.HeartbeatRequest
	13, // 16: lauradb.cluster.ClusterService.GetTopology:input_type -> lauradb.cluster.GetTopologyRequest
	3,  // 17: lauradb.cluster.ClusterService.RegisterNode:output_type -> lauradb.cluster.NodeRegistrationResponse
	5,  // 18: lauradb.cluster.ClusterService.DeregisterNode:output_type -> lauradb.cluster.NodeDeregistrationResponse
	10, // 19: lauradb.cluster.ClusterService.Heartbeat:output_type -> lauradb.cluster.HeartbeatResponse
	6,  // 20: lauradb.cluster.ClusterService.GetTopology:output_type -> lauradb.cluster.ClusterTopology
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pkg_cluster_proto_cluster_proto_init() }
func file_pkg_cluster_proto_cluster_proto_init() {
	if File_pkg_cluster_proto_cluster_proto != nil {
		return
	}
	file_pkg_cluster_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_cluster_proto_cluster_proto_rawDesc), len(file_pkg_cluster_proto_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_cluster_proto_cluster_proto_goTypes,
		DependencyIndexes: file_pkg_cluster_proto_cluster_proto_depIdxs,
		EnumInfos:         file_pkg_cluster_proto_cluster_proto_enumTypes,
		MessageInfos:      file_pkg_cluster_proto_cluster_proto_msgTypes,
	}.Build()
	File_pkg_cluster_proto_cluster_proto = out.File
	file_pkg_cluster_proto_cluster_proto_goTypes = nil
	file_pkg_cluster_proto_cluster_proto_depIdxs = nil
}
