// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/cluster/proto/common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common operation type used across multiple services
type OperationType int32

const (
	OperationType_UNKNOWN_OP        OperationType = 0
	OperationType_INSERT            OperationType = 1
	OperationType_UPDATE            OperationType = 2
	OperationType_DELETE            OperationType = 3
	OperationType_CREATE_COLLECTION OperationType = 4
	OperationType_DROP_COLLECTION   OperationType = 5
	OperationType_CREATE_INDEX      OperationType = 6
	OperationType_DROP_INDEX        OperationType = 7
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "UNKNOWN_OP",
		1: "INSERT",
		2: "UPDATE",
		3: "DELETE",
		4: "CREATE_COLLECTION",
		5: "DROP_COLLECTION",
		6: "CREATE_INDEX",
		7: "DROP_INDEX",
	}
	OperationType_value = map[string]int32{
		"UNKNOWN_OP":        0,
		"INSERT":            1,
		"UPDATE":            2,
		"DELETE":            3,
		"CREATE_COLLECTION": 4,
		"DROP_COLLECTION":   5,
		"CREATE_INDEX":      6,
		"DROP_INDEX":        7,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_cluster_proto_common_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_pkg_cluster_proto_common_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_common_proto_rawDescGZIP(), []int{0}
}

// ChunkRange represents a range of shard keys
type ChunkRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	MinKey        []byte                 `protobuf:"bytes,2,opt,name=min_key,json=minKey,proto3" json:"min_key,omitempty"` // Minimum shard key value (serialized)
	MaxKey        []byte                 `protobuf:"bytes,3,opt,name=max_key,json=maxKey,proto3" json:"max_key,omitempty"` // Maximum shard key value (serialized)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRange) Reset() {
	*x = ChunkRange{}
	mi := &file_pkg_cluster_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRange) ProtoMessage() {}

func (x *ChunkRange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRange.ProtoReflect.Descriptor instead.
func (*ChunkRange) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkRange) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkRange) GetMinKey() []byte {
	if x != nil {
		return x.MinKey
	}
	return nil
}

func (x *ChunkRange) GetMaxKey() []byte {
	if x != nil {
		return x.MaxKey
	}
	return nil
}

var File_pkg_cluster_proto_common_proto protoreflect.FileDescriptor

const file_pkg_cluster_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/cluster/proto/common.proto\x12\x0flauradb.cluster\"Y\n" +
	"\n" +
	"ChunkRange\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x17\n" +
	"\amin_key\x18\x02 \x01(\fR\x06minKey\x12\x17\n" +
	"\amax_key\x18\x03 \x01(\fR\x06maxKey*\x91\x01\n" +
	"\rOperationType\x12\x0e\n" +
	"\n" +
	"UNKNOWN_OP\x10\x00\x12\n" +
	"\n" +
	"\x06INSERT\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\x15\n" +
	"\x11CREATE_COLLECTION\x10\x04\x12\x13\n" +
	"\x0fDROP_COLLECTION\x10\x05\x12\x10\n" +
	"\fCREATE_INDEX\x10\x06\x12\x0e\n" +
	"\n" +
	"DROP_INDEX\x10\aB1Z/github.com/mnohosten/laura-db/pkg/cluster/protob\x06proto3"

var (
	file_pkg_cluster_proto_common_proto_rawDescOnce sync.Once
	file_pkg_cluster_proto_common_proto_rawDescData []byte
)

func file_pkg_cluster_proto_common_proto_rawDescGZIP() []byte {
	file_pkg_cluster_proto_common_proto_rawDescOnce.Do(func() {
		file_pkg_cluster_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_cluster_proto_common_proto_rawDesc), len(file_pkg_cluster_proto_common_proto_rawDesc)))
	})
	return file_pkg_cluster_proto_common_proto_rawDescData
}

var file_pkg_cluster_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_cluster_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_cluster_proto_common_proto_goTypes = []any{
	(OperationType)(0), // 0: lauradb.cluster.OperationType
	(*ChunkRange)(nil), // 1: lauradb.cluster.ChunkRange
}
var file_pkg_cluster_proto_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_cluster_proto_common_proto_init() }
func file_pkg_cluster_proto_common_proto_init() {
	if File_pkg_cluster_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_cluster_proto_common_proto_rawDesc), len(file_pkg_cluster_proto_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_cluster_proto_common_proto_goTypes,
		DependencyIndexes: file_pkg_cluster_proto_common_proto_depIdxs,
		EnumInfos:         file_pkg_cluster_proto_common_proto_enumTypes,
		MessageInfos:      file_pkg_cluster_proto_common_proto_msgTypes,
	}.Build()
	File_pkg_cluster_proto_common_proto = out.File
	file_pkg_cluster_proto_common_proto_goTypes = nil
	file_pkg_cluster_proto_common_proto_depIdxs = nil
}
