// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: pkg/cluster/proto/replication.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReplicationService_StreamOplog_FullMethodName      = "/lauradb.cluster.ReplicationService/StreamOplog"
	ReplicationService_InitialSync_FullMethodName      = "/lauradb.cluster.ReplicationService/InitialSync"
	ReplicationService_RequestVote_FullMethodName      = "/lauradb.cluster.ReplicationService/RequestVote"
	ReplicationService_AcknowledgeWrite_FullMethodName = "/lauradb.cluster.ReplicationService/AcknowledgeWrite"
	ReplicationService_AppendOplog_FullMethodName      = "/lauradb.cluster.ReplicationService/AppendOplog"
)

// ReplicationServiceClient is the client API for ReplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReplicationService handles data replication
type ReplicationServiceClient interface {
	// Stream oplog entries to a replica
	StreamOplog(ctx context.Context, in *ReplicationStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReplicationStreamResponse], error)
	// Perform initial sync for a new replica
	InitialSync(ctx context.Context, in *InitialSyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InitialSyncResponse], error)
	// Request vote during election
	RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
	// Acknowledge write replication
	AcknowledgeWrite(ctx context.Context, in *WriteAcknowledgmentRequest, opts ...grpc.CallOption) (*WriteAcknowledgmentResponse, error)
	// Append oplog entry (called by primary)
	AppendOplog(ctx context.Context, in *OplogEntry, opts ...grpc.CallOption) (*AppendOplogResponse, error)
}

type replicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationServiceClient(cc grpc.ClientConnInterface) ReplicationServiceClient {
	return &replicationServiceClient{cc}
}

func (c *replicationServiceClient) StreamOplog(ctx context.Context, in *ReplicationStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReplicationStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReplicationService_ServiceDesc.Streams[0], ReplicationService_StreamOplog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplicationStreamRequest, ReplicationStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplicationService_StreamOplogClient = grpc.ServerStreamingClient[ReplicationStreamResponse]

func (c *replicationServiceClient) InitialSync(ctx context.Context, in *InitialSyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InitialSyncResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReplicationService_ServiceDesc.Streams[1], ReplicationService_InitialSync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InitialSyncRequest, InitialSyncResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplicationService_InitialSyncClient = grpc.ServerStreamingClient[InitialSyncResponse]

func (c *replicationServiceClient) RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, ReplicationService_RequestVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) AcknowledgeWrite(ctx context.Context, in *WriteAcknowledgmentRequest, opts ...grpc.CallOption) (*WriteAcknowledgmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteAcknowledgmentResponse)
	err := c.cc.Invoke(ctx, ReplicationService_AcknowledgeWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) AppendOplog(ctx context.Context, in *OplogEntry, opts ...grpc.CallOption) (*AppendOplogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendOplogResponse)
	err := c.cc.Invoke(ctx, ReplicationService_AppendOplog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicationServiceServer is the server API for ReplicationService service.
// All implementations must embed UnimplementedReplicationServiceServer
// for forward compatibility.
//
// ReplicationService handles data replication
type ReplicationServiceServer interface {
	// Stream oplog entries to a replica
	StreamOplog(*ReplicationStreamRequest, grpc.ServerStreamingServer[ReplicationStreamResponse]) error
	// Perform initial sync for a new replica
	InitialSync(*InitialSyncRequest, grpc.ServerStreamingServer[InitialSyncResponse]) error
	// Request vote during election
	RequestVote(context.Context, *VoteRequest) (*VoteResponse, error)
	// Acknowledge write replication
	AcknowledgeWrite(context.Context, *WriteAcknowledgmentRequest) (*WriteAcknowledgmentResponse, error)
	// Append oplog entry (called by primary)
	AppendOplog(context.Context, *OplogEntry) (*AppendOplogResponse, error)
	mustEmbedUnimplementedReplicationServiceServer()
}

// UnimplementedReplicationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicationServiceServer struct{}

func (UnimplementedReplicationServiceServer) StreamOplog(*ReplicationStreamRequest, grpc.ServerStreamingServer[ReplicationStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamOplog not implemented")
}
func (UnimplementedReplicationServiceServer) InitialSync(*InitialSyncRequest, grpc.ServerStreamingServer[InitialSyncResponse]) error {
	return status.Errorf(codes.Unimplemented, "method InitialSync not implemented")
}
func (UnimplementedReplicationServiceServer) RequestVote(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedReplicationServiceServer) AcknowledgeWrite(context.Context, *WriteAcknowledgmentRequest) (*WriteAcknowledgmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeWrite not implemented")
}
func (UnimplementedReplicationServiceServer) AppendOplog(context.Context, *OplogEntry) (*AppendOplogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendOplog not implemented")
}
func (UnimplementedReplicationServiceServer) mustEmbedUnimplementedReplicationServiceServer() {}
func (UnimplementedReplicationServiceServer) testEmbeddedByValue()                            {}

// UnsafeReplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServiceServer will
// result in compilation errors.
type UnsafeReplicationServiceServer interface {
	mustEmbedUnimplementedReplicationServiceServer()
}

func RegisterReplicationServiceServer(s grpc.ServiceRegistrar, srv ReplicationServiceServer) {
	// If the following call pancis, it indicates UnimplementedReplicationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReplicationService_ServiceDesc, srv)
}

func _ReplicationService_StreamOplog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReplicationStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplicationServiceServer).StreamOplog(m, &grpc.GenericServerStream[ReplicationStreamRequest, ReplicationStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplicationService_StreamOplogServer = grpc.ServerStreamingServer[ReplicationStreamResponse]

func _ReplicationService_InitialSync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitialSyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplicationServiceServer).InitialSync(m, &grpc.GenericServerStream[InitialSyncRequest, InitialSyncResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplicationService_InitialSyncServer = grpc.ServerStreamingServer[InitialSyncResponse]

func _ReplicationService_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_RequestVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).RequestVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_AcknowledgeWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteAcknowledgmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).AcknowledgeWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_AcknowledgeWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).AcknowledgeWrite(ctx, req.(*WriteAcknowledgmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_AppendOplog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OplogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).AppendOplog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_AppendOplog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).AppendOplog(ctx, req.(*OplogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicationService_ServiceDesc is the grpc.ServiceDesc for ReplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lauradb.cluster.ReplicationService",
	HandlerType: (*ReplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _ReplicationService_RequestVote_Handler,
		},
		{
			MethodName: "AcknowledgeWrite",
			Handler:    _ReplicationService_AcknowledgeWrite_Handler,
		},
		{
			MethodName: "AppendOplog",
			Handler:    _ReplicationService_AppendOplog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamOplog",
			Handler:       _ReplicationService_StreamOplog_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InitialSync",
			Handler:       _ReplicationService_InitialSync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/cluster/proto/replication.proto",
}
