// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/cluster/proto/replication.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OplogEntry represents a single operation in the replication log
type OplogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpId          int64                  `protobuf:"varint,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`                                          // Monotonically increasing operation ID
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                            // Unix timestamp in milliseconds
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`                                             // Database.Collection
	OpType        OperationType          `protobuf:"varint,4,opt,name=op_type,json=opType,proto3,enum=lauradb.cluster.OperationType" json:"op_type,omitempty"` // Type of operation
	Document      []byte                 `protobuf:"bytes,5,opt,name=document,proto3" json:"document,omitempty"`                                               // Serialized document (BSON)
	Query         []byte                 `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`                                                     // Serialized query for updates/deletes
	Update        []byte                 `protobuf:"bytes,7,opt,name=update,proto3" json:"update,omitempty"`                                                   // Serialized update operators
	TxnId         int64                  `protobuf:"varint,8,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`                                       // Transaction ID (0 if not in transaction)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OplogEntry) Reset() {
	*x = OplogEntry{}
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OplogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OplogEntry) ProtoMessage() {}

func (x *OplogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OplogEntry.ProtoReflect.Descriptor instead.
func (*OplogEntry) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_replication_proto_rawDescGZIP(), []int{0}
}

func (x *OplogEntry) GetOpId() int64 {
	if x != nil {
		return x.OpId
	}
	return 0
}

func (x *OplogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OplogEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *OplogEntry) GetOpType() OperationType {
	if x != nil {
		return x.OpType
	}
	return OperationType_UNKNOWN_OP
}

func (x *OplogEntry) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *OplogEntry) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *OplogEntry) GetUpdate() []byte {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *OplogEntry) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

// ReplicationStreamRequest initiates oplog streaming
type ReplicationStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`             // ID of the requesting replica
	StartOplogId  int64                  `protobuf:"varint,2,opt,name=start_oplog_id,json=startOplogId,proto3" json:"start_oplog_id,omitempty"` // Start streaming from this oplog ID
	InitialSync   bool                   `protobuf:"varint,3,opt,name=initial_sync,json=initialSync,proto3" json:"initial_sync,omitempty"`      // True if this is initial sync
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationStreamRequest) Reset() {
	*x = ReplicationStreamRequest{}
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationStreamRequest) ProtoMessage() {}

func (x *ReplicationStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationStreamRequest.ProtoReflect.Descriptor instead.
func (*ReplicationStreamRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_replication_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicationStreamRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *ReplicationStreamRequest) GetStartOplogId() int64 {
	if x != nil {
		return x.StartOplogId
	}
	return 0
}

func (x *ReplicationStreamRequest) GetInitialSync() bool {
	if x != nil {
		return x.InitialSync
	}
	return false
}

// ReplicationStreamResponse streams oplog entries
type ReplicationStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*OplogEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	LatestOplogId int64                  `protobuf:"varint,2,opt,name=latest_oplog_id,json=latestOplogId,proto3" json:"latest_oplog_id,omitempty"` // Latest oplog ID on primary
	MoreAvailable bool                   `protobuf:"varint,3,opt,name=more_available,json=moreAvailable,proto3" json:"more_available,omitempty"`   // True if more entries available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationStreamResponse) Reset() {
	*x = ReplicationStreamResponse{}
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationStreamResponse) ProtoMessage() {}

func (x *ReplicationStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationStreamResponse.ProtoReflect.Descriptor instead.
func (*ReplicationStreamResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_replication_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicationStreamResponse) GetEntries() []*OplogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ReplicationStreamResponse) GetLatestOplogId() int64 {
	if x != nil {
		return x.LatestOplogId
	}
	return 0
}

func (x *ReplicationStreamResponse) GetMoreAvailable() bool {
	if x != nil {
		return x.MoreAvailable
	}
	return false
}

// InitialSyncRequest requests full data copy
type InitialSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Collections   []string               `protobuf:"bytes,2,rep,name=collections,proto3" json:"collections,omitempty"` // Empty means all collections
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialSyncRequest) Reset() {
	*x = InitialSyncRequest{}
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSyncRequest) ProtoMessage() {}

func (x *InitialSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSyncRequest.ProtoReflect.Descriptor instead.
func (*InitialSyncRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_replication_proto_rawDescGZIP(), []int{3}
}

func (x *InitialSyncRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *InitialSyncRequest) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

type InitialSyncResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DataChunk        []byte                 `protobuf:"bytes,1,opt,name=data_chunk,json=dataChunk,proto3" json:"data_chunk,omitempty"`                           // Chunk of serialized data
	Complete         bool                   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`                                             // True when sync is complete
	SyncPointOplogId int64                  `protobuf:"varint,3,opt,name=sync_point_oplog_id,json=syncPointOplogId,proto3" json:"sync_point_oplog_id,omitempty"` // Oplog ID at time of snapshot
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InitialSyncResponse) Reset() {
	*x = InitialSyncResponse{}
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSyncResponse) ProtoMessage() {}

func (x *InitialSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSyncResponse.ProtoReflect.Descriptor instead.
func (*InitialSyncResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_replication_proto_rawDescGZIP(), []int{4}
}

func (x *InitialSyncResponse) GetDataChunk() []byte {
	if x != nil {
		return x.DataChunk
	}
	return nil
}

func (x *InitialSyncResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *InitialSyncResponse) GetSyncPointOplogId() int64 {
	if x != nil {
		return x.SyncPointOplogId
	}
	return 0
}

// Election messages for leader election
type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`                                    // Election term
	LastOplogId   int64                  `protobuf:"varint,3,opt,name=last_oplog_id,json=lastOplogId,proto3" json:"last_oplog_id,omitempty"` // Last oplog ID on candidate
	Priority      int64                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`                            // Candidate priority
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_replication_proto_rawDescGZIP(), []int{5}
}

func (x *VoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *VoteRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteRequest) GetLastOplogId() int64 {
	if x != nil {
		return x.LastOplogId
	}
	return 0
}

func (x *VoteRequest) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteGranted   bool                   `protobuf:"varint,1,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	VoterId       string                 `protobuf:"bytes,3,opt,name=voter_id,json=voterId,proto3" json:"voter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_replication_proto_rawDescGZIP(), []int{6}
}

func (x *VoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

func (x *VoteResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteResponse) GetVoterId() string {
	if x != nil {
		return x.VoterId
	}
	return ""
}

// Write concern for replication
type WriteAcknowledgment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	OplogId       int64                  `protobuf:"varint,2,opt,name=oplog_id,json=oplogId,proto3" json:"oplog_id,omitempty"` // Oplog ID that was applied
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteAcknowledgment) Reset() {
	*x = WriteAcknowledgment{}
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAcknowledgment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAcknowledgment) ProtoMessage() {}

func (x *WriteAcknowledgment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAcknowledgment.ProtoReflect.Descriptor instead.
func (*WriteAcknowledgment) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_replication_proto_rawDescGZIP(), []int{7}
}

func (x *WriteAcknowledgment) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WriteAcknowledgment) GetOplogId() int64 {
	if x != nil {
		return x.OplogId
	}
	return 0
}

func (x *WriteAcknowledgment) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteAcknowledgment) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WriteAcknowledgmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acks          []*WriteAcknowledgment `protobuf:"bytes,1,rep,name=acks,proto3" json:"acks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteAcknowledgmentRequest) Reset() {
	*x = WriteAcknowledgmentRequest{}
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAcknowledgmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAcknowledgmentRequest) ProtoMessage() {}

func (x *WriteAcknowledgmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAcknowledgmentRequest.ProtoReflect.Descriptor instead.
func (*WriteAcknowledgmentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_replication_proto_rawDescGZIP(), []int{8}
}

func (x *WriteAcknowledgmentRequest) GetAcks() []*WriteAcknowledgment {
	if x != nil {
		return x.Acks
	}
	return nil
}

type WriteAcknowledgmentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AllAcknowledged bool                   `protobuf:"varint,1,opt,name=all_acknowledged,json=allAcknowledged,proto3" json:"all_acknowledged,omitempty"`
	AckCount        int32                  `protobuf:"varint,2,opt,name=ack_count,json=ackCount,proto3" json:"ack_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WriteAcknowledgmentResponse) Reset() {
	*x = WriteAcknowledgmentResponse{}
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAcknowledgmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAcknowledgmentResponse) ProtoMessage() {}

func (x *WriteAcknowledgmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAcknowledgmentResponse.ProtoReflect.Descriptor instead.
func (*WriteAcknowledgmentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_replication_proto_rawDescGZIP(), []int{9}
}

func (x *WriteAcknowledgmentResponse) GetAllAcknowledged() bool {
	if x != nil {
		return x.AllAcknowledged
	}
	return false
}

func (x *WriteAcknowledgmentResponse) GetAckCount() int32 {
	if x != nil {
		return x.AckCount
	}
	return 0
}

type AppendOplogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OplogId       int64                  `protobuf:"varint,2,opt,name=oplog_id,json=oplogId,proto3" json:"oplog_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendOplogResponse) Reset() {
	*x = AppendOplogResponse{}
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendOplogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendOplogResponse) ProtoMessage() {}

func (x *AppendOplogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_replication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendOplogResponse.ProtoReflect.Descriptor instead.
func (*AppendOplogResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_replication_proto_rawDescGZIP(), []int{10}
}

func (x *AppendOplogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendOplogResponse) GetOplogId() int64 {
	if x != nil {
		return x.OplogId
	}
	return 0
}

func (x *AppendOplogResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_cluster_proto_replication_proto protoreflect.FileDescriptor

const file_pkg_cluster_proto_replication_proto_rawDesc = "" +
	"\n" +
	"#pkg/cluster/proto/replication.proto\x12\x0flauradb.cluster\x1a\x1epkg/cluster/proto/common.proto\"\xf7\x01\n" +
	"\n" +
	"OplogEntry\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\x03R\x04opId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x127\n" +
	"\aop_type\x18\x04 \x01(\x0e2\x1e.lauradb.cluster.OperationTypeR\x06opType\x12\x1a\n" +
	"\bdocument\x18\x05 \x01(\fR\bdocument\x12\x14\n" +
	"\x05query\x18\x06 \x01(\fR\x05query\x12\x16\n" +
	"\x06update\x18\a \x01(\fR\x06update\x12\x15\n" +
	"\x06txn_id\x18\b \x01(\x03R\x05txnId\"\x82\x01\n" +
	"\x18ReplicationStreamRequest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12$\n" +
	"\x0estart_oplog_id\x18\x02 \x01(\x03R\fstartOplogId\x12!\n" +
	"\finitial_sync\x18\x03 \x01(\bR\vinitialSync\"\xa1\x01\n" +
	"\x19ReplicationStreamResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.lauradb.cluster.OplogEntryR\aentries\x12&\n" +
	"\x0flatest_oplog_id\x18\x02 \x01(\x03R\rlatestOplogId\x12%\n" +
	"\x0emore_available\x18\x03 \x01(\bR\rmoreAvailable\"U\n" +
	"\x12InitialSyncRequest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12 \n" +
	"\vcollections\x18\x02 \x03(\tR\vcollections\"\x7f\n" +
	"\x13InitialSyncResponse\x12\x1d\n" +
	"\n" +
	"data_chunk\x18\x01 \x01(\fR\tdataChunk\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete\x12-\n" +
	"\x13sync_point_oplog_id\x18\x03 \x01(\x03R\x10syncPointOplogId\"\x84\x01\n" +
	"\vVoteRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\"\n" +
	"\rlast_oplog_id\x18\x03 \x01(\x03R\vlastOplogId\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x03R\bpriority\"`\n" +
	"\fVoteResponse\x12!\n" +
	"\fvote_granted\x18\x01 \x01(\bR\vvoteGranted\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\x19\n" +
	"\bvoter_id\x18\x03 \x01(\tR\avoterId\"y\n" +
	"\x13WriteAcknowledgment\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\boplog_id\x18\x02 \x01(\x03R\aoplogId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"V\n" +
	"\x1aWriteAcknowledgmentRequest\x128\n" +
	"\x04acks\x18\x01 \x03(\v2$.lauradb.cluster.WriteAcknowledgmentR\x04acks\"e\n" +
	"\x1bWriteAcknowledgmentResponse\x12)\n" +
	"\x10all_acknowledged\x18\x01 \x01(\bR\x0fallAcknowledged\x12\x1b\n" +
	"\tack_count\x18\x02 \x01(\x05R\backCount\"`\n" +
	"\x13AppendOplogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\boplog_id\x18\x02 \x01(\x03R\aoplogId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xe5\x03\n" +
	"\x12ReplicationService\x12f\n" +
	"\vStreamOplog\x12).lauradb.cluster.ReplicationStreamRequest\x1a*.lauradb.cluster.ReplicationStreamResponse0\x01\x12Z\n" +
	"\vInitialSync\x12#.lauradb.cluster.InitialSyncRequest\x1a$.lauradb.cluster.InitialSyncResponse0\x01\x12J\n" +
	"\vRequestVote\x12\x1c.lauradb.cluster.VoteRequest\x1a\x1d.lauradb.cluster.VoteResponse\x12m\n" +
	"\x10AcknowledgeWrite\x12+.lauradb.cluster.WriteAcknowledgmentRequest\x1a,.lauradb.cluster.WriteAcknowledgmentResponse\x12P\n" +
	"\vAppendOplog\x12\x1b.lauradb.cluster.OplogEntry\x1a$.lauradb.cluster.AppendOplogResponseB1Z/github.com/mnohosten/laura-db/pkg/cluster/protob\x06proto3"

var (
	file_pkg_cluster_proto_replication_proto_rawDescOnce sync.Once
	file_pkg_cluster_proto_replication_proto_rawDescData []byte
)

func file_pkg_cluster_proto_replication_proto_rawDescGZIP() []byte {
	file_pkg_cluster_proto_replication_proto_rawDescOnce.Do(func() {
		file_pkg_cluster_proto_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_cluster_proto_replication_proto_rawDesc), len(file_pkg_cluster_proto_replication_proto_rawDesc)))
	})
	return file_pkg_cluster_proto_replication_proto_rawDescData
}

var file_pkg_cluster_proto_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_cluster_proto_replication_proto_goTypes = []any{
	(*OplogEntry)(nil),                  // 0: lauradb.cluster.OplogEntry
	(*ReplicationStreamRequest)(nil),    // 1: lauradb.cluster.ReplicationStreamRequest
	(*ReplicationStreamResponse)(nil),   // 2: lauradb.cluster.ReplicationStreamResponse
	(*InitialSyncRequest)(nil),          // 3: lauradb.cluster.InitialSyncRequest
	(*InitialSyncResponse)(nil),         // 4: lauradb.cluster.InitialSyncResponse
	(*VoteRequest)(nil),                 // 5: lauradb.cluster.VoteRequest
	(*VoteResponse)(nil),                // 6: lauradb.cluster.VoteResponse
	(*WriteAcknowledgment)(nil),         // 7: lauradb.cluster.WriteAcknowledgment
	(*WriteAcknowledgmentRequest)(nil),  // 8: lauradb.cluster.WriteAcknowledgmentRequest
	(*WriteAcknowledgmentResponse)(nil), // 9: lauradb.cluster.WriteAcknowledgmentResponse
	(*AppendOplogResponse)(nil),         // 10: lauradb.cluster.AppendOplogResponse
	(OperationType)(0),                  // 11: lauradb.cluster.OperationType
}
var file_pkg_cluster_proto_replication_proto_depIdxs = []int32{
	11, // 0: lauradb.cluster.OplogEntry.op_type:type_name -> lauradb.cluster.OperationType
	0,  // 1: lauradb.cluster.ReplicationStreamResponse.entries:type_name -> lauradb.cluster.OplogEntry
	7,  // 2: lauradb.cluster.WriteAcknowledgmentRequest.acks:type_name -> lauradb.cluster.WriteAcknowledgment
	1,  // 3: lauradb.cluster.ReplicationService.StreamOplog:input_type -> lauradb.cluster.ReplicationStreamRequest
	3,  // 4: lauradb.cluster.ReplicationService.InitialSync:input_type -> lauradb.cluster.InitialSyncRequest
	5,  // 5: lauradb.cluster.ReplicationService.RequestVote:input_type -> lauradb.cluster.VoteRequest
	8,  // 6: lauradb.cluster.ReplicationService.AcknowledgeWrite:input_type -> lauradb.cluster.WriteAcknowledgmentRequest
	0,  // 7: lauradb.cluster.ReplicationService.AppendOplog:input_type -> lauradb.cluster.OplogEntry
	2,  // 8: lauradb.cluster.ReplicationService.StreamOplog:output_type -> lauradb.cluster.ReplicationStreamResponse
	4,  // 9: lauradb.cluster.ReplicationService.InitialSync:output_type -> lauradb.cluster.InitialSyncResponse
	6,  // 10: lauradb.cluster.ReplicationService.RequestVote:output_type -> lauradb.cluster.VoteResponse
	9,  // 11: lauradb.cluster.ReplicationService.AcknowledgeWrite:output_type -> lauradb.cluster.WriteAcknowledgmentResponse
	10, // 12: lauradb.cluster.ReplicationService.AppendOplog:output_type -> lauradb.cluster.AppendOplogResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_cluster_proto_replication_proto_init() }
func file_pkg_cluster_proto_replication_proto_init() {
	if File_pkg_cluster_proto_replication_proto != nil {
		return
	}
	file_pkg_cluster_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_cluster_proto_replication_proto_rawDesc), len(file_pkg_cluster_proto_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_cluster_proto_replication_proto_goTypes,
		DependencyIndexes: file_pkg_cluster_proto_replication_proto_depIdxs,
		MessageInfos:      file_pkg_cluster_proto_replication_proto_msgTypes,
	}.Build()
	File_pkg_cluster_proto_replication_proto = out.File
	file_pkg_cluster_proto_replication_proto_goTypes = nil
	file_pkg_cluster_proto_replication_proto_depIdxs = nil
}
