// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/cluster/proto/routing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShardingStrategy int32

const (
	ShardingStrategy_UNKNOWN_STRATEGY ShardingStrategy = 0
	ShardingStrategy_HASH             ShardingStrategy = 1
	ShardingStrategy_RANGE            ShardingStrategy = 2
	ShardingStrategy_COMPOUND         ShardingStrategy = 3
)

// Enum value maps for ShardingStrategy.
var (
	ShardingStrategy_name = map[int32]string{
		0: "UNKNOWN_STRATEGY",
		1: "HASH",
		2: "RANGE",
		3: "COMPOUND",
	}
	ShardingStrategy_value = map[string]int32{
		"UNKNOWN_STRATEGY": 0,
		"HASH":             1,
		"RANGE":            2,
		"COMPOUND":         3,
	}
)

func (x ShardingStrategy) Enum() *ShardingStrategy {
	p := new(ShardingStrategy)
	*p = x
	return p
}

func (x ShardingStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShardingStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_cluster_proto_routing_proto_enumTypes[0].Descriptor()
}

func (ShardingStrategy) Type() protoreflect.EnumType {
	return &file_pkg_cluster_proto_routing_proto_enumTypes[0]
}

func (x ShardingStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShardingStrategy.Descriptor instead.
func (ShardingStrategy) EnumDescriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{0}
}

// QueryRequest represents a query to be routed to appropriate shard(s)
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Unique request identifier
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Query         []byte                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`           // Serialized query (BSON)
	Projection    []byte                 `protobuf:"bytes,5,opt,name=projection,proto3" json:"projection,omitempty"` // Serialized projection
	Limit         int64                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip          int64                  `protobuf:"varint,7,opt,name=skip,proto3" json:"skip,omitempty"`
	Sort          []byte                 `protobuf:"bytes,8,opt,name=sort,proto3" json:"sort,omitempty"`                         // Serialized sort spec
	ShardKey      []byte                 `protobuf:"bytes,9,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"` // Serialized shard key value (for targeted queries)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QueryRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *QueryRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *QueryRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *QueryRequest) GetProjection() []byte {
	if x != nil {
		return x.Projection
	}
	return nil
}

func (x *QueryRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRequest) GetSkip() int64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *QueryRequest) GetSort() []byte {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *QueryRequest) GetShardKey() []byte {
	if x != nil {
		return x.ShardKey
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Documents     [][]byte               `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`                               // Serialized documents (BSON)
	MoreAvailable bool                   `protobuf:"varint,3,opt,name=more_available,json=moreAvailable,proto3" json:"more_available,omitempty"` // True if pagination needed
	CursorId      string                 `protobuf:"bytes,4,opt,name=cursor_id,json=cursorId,proto3" json:"cursor_id,omitempty"`                 // For paginated results
	Stats         *QueryStats            `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QueryResponse) GetDocuments() [][]byte {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *QueryResponse) GetMoreAvailable() bool {
	if x != nil {
		return x.MoreAvailable
	}
	return false
}

func (x *QueryResponse) GetCursorId() string {
	if x != nil {
		return x.CursorId
	}
	return ""
}

func (x *QueryResponse) GetStats() *QueryStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type QueryStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DocumentsExamined int32                  `protobuf:"varint,1,opt,name=documents_examined,json=documentsExamined,proto3" json:"documents_examined,omitempty"`
	DocumentsReturned int32                  `protobuf:"varint,2,opt,name=documents_returned,json=documentsReturned,proto3" json:"documents_returned,omitempty"`
	ExecutionTimeMs   int64                  `protobuf:"varint,3,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	ShardsQueried     []string               `protobuf:"bytes,4,rep,name=shards_queried,json=shardsQueried,proto3" json:"shards_queried,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryStats) Reset() {
	*x = QueryStats{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStats) ProtoMessage() {}

func (x *QueryStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStats.ProtoReflect.Descriptor instead.
func (*QueryStats) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{2}
}

func (x *QueryStats) GetDocumentsExamined() int32 {
	if x != nil {
		return x.DocumentsExamined
	}
	return 0
}

func (x *QueryStats) GetDocumentsReturned() int32 {
	if x != nil {
		return x.DocumentsReturned
	}
	return 0
}

func (x *QueryStats) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *QueryStats) GetShardsQueried() []string {
	if x != nil {
		return x.ShardsQueried
	}
	return nil
}

// InsertRequest represents document insertion
type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Documents     [][]byte               `protobuf:"bytes,4,rep,name=documents,proto3" json:"documents,omitempty"` // Serialized documents to insert
	Ordered       bool                   `protobuf:"varint,5,opt,name=ordered,proto3" json:"ordered,omitempty"`    // Stop on first error if true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{3}
}

func (x *InsertRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InsertRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *InsertRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertRequest) GetDocuments() [][]byte {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *InsertRequest) GetOrdered() bool {
	if x != nil {
		return x.Ordered
	}
	return false
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	InsertedCount int32                  `protobuf:"varint,2,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"`
	Errors        []*InsertError         `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{4}
}

func (x *InsertResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InsertResponse) GetInsertedCount() int32 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

func (x *InsertResponse) GetErrors() []*InsertError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type InsertError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertError) Reset() {
	*x = InsertError{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertError) ProtoMessage() {}

func (x *InsertError) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertError.ProtoReflect.Descriptor instead.
func (*InsertError) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{5}
}

func (x *InsertError) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *InsertError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// UpdateRequest represents document update
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Query         []byte                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`   // Serialized query filter
	Update        []byte                 `protobuf:"bytes,5,opt,name=update,proto3" json:"update,omitempty"` // Serialized update operators
	Multi         bool                   `protobuf:"varint,6,opt,name=multi,proto3" json:"multi,omitempty"`  // Update multiple documents
	Upsert        bool                   `protobuf:"varint,7,opt,name=upsert,proto3" json:"upsert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UpdateRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *UpdateRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *UpdateRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *UpdateRequest) GetUpdate() []byte {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *UpdateRequest) GetMulti() bool {
	if x != nil {
		return x.Multi
	}
	return false
}

func (x *UpdateRequest) GetUpsert() bool {
	if x != nil {
		return x.Upsert
	}
	return false
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MatchedCount  int32                  `protobuf:"varint,2,opt,name=matched_count,json=matchedCount,proto3" json:"matched_count,omitempty"`
	ModifiedCount int32                  `protobuf:"varint,3,opt,name=modified_count,json=modifiedCount,proto3" json:"modified_count,omitempty"`
	UpsertedCount int32                  `protobuf:"varint,4,opt,name=upserted_count,json=upsertedCount,proto3" json:"upserted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UpdateResponse) GetMatchedCount() int32 {
	if x != nil {
		return x.MatchedCount
	}
	return 0
}

func (x *UpdateResponse) GetModifiedCount() int32 {
	if x != nil {
		return x.ModifiedCount
	}
	return 0
}

func (x *UpdateResponse) GetUpsertedCount() int32 {
	if x != nil {
		return x.UpsertedCount
	}
	return 0
}

// DeleteRequest represents document deletion
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Query         []byte                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`  // Serialized query filter
	Multi         bool                   `protobuf:"varint,5,opt,name=multi,proto3" json:"multi,omitempty"` // Delete multiple documents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeleteRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DeleteRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *DeleteRequest) GetMulti() bool {
	if x != nil {
		return x.Multi
	}
	return false
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeleteResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

// AggregationRequest represents aggregation pipeline
type AggregationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Pipeline      [][]byte               `protobuf:"bytes,4,rep,name=pipeline,proto3" json:"pipeline,omitempty"` // Serialized pipeline stages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregationRequest) Reset() {
	*x = AggregationRequest{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationRequest) ProtoMessage() {}

func (x *AggregationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationRequest.ProtoReflect.Descriptor instead.
func (*AggregationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{10}
}

func (x *AggregationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AggregationRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *AggregationRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *AggregationRequest) GetPipeline() [][]byte {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type AggregationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Results       [][]byte               `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"` // Serialized result documents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregationResponse) Reset() {
	*x = AggregationResponse{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationResponse) ProtoMessage() {}

func (x *AggregationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationResponse.ProtoReflect.Descriptor instead.
func (*AggregationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{11}
}

func (x *AggregationResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AggregationResponse) GetResults() [][]byte {
	if x != nil {
		return x.Results
	}
	return nil
}

// Shard routing information
type ShardRouteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Chunks        []*ChunkRange          `protobuf:"bytes,5,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardRouteInfo) Reset() {
	*x = ShardRouteInfo{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardRouteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardRouteInfo) ProtoMessage() {}

func (x *ShardRouteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardRouteInfo.ProtoReflect.Descriptor instead.
func (*ShardRouteInfo) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{12}
}

func (x *ShardRouteInfo) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardRouteInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ShardRouteInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ShardRouteInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ShardRouteInfo) GetChunks() []*ChunkRange {
	if x != nil {
		return x.Chunks
	}
	return nil
}

// Config server messages for routing metadata
type GetShardMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // Current version, return only if newer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardMapRequest) Reset() {
	*x = GetShardMapRequest{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardMapRequest) ProtoMessage() {}

func (x *GetShardMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardMapRequest.ProtoReflect.Descriptor instead.
func (*GetShardMapRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{13}
}

func (x *GetShardMapRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *GetShardMapRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetShardMapRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetShardMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Shards        []*ShardRouteInfo      `protobuf:"bytes,2,rep,name=shards,proto3" json:"shards,omitempty"`
	ShardKeyField string                 `protobuf:"bytes,3,opt,name=shard_key_field,json=shardKeyField,proto3" json:"shard_key_field,omitempty"`
	Strategy      ShardingStrategy       `protobuf:"varint,4,opt,name=strategy,proto3,enum=lauradb.cluster.ShardingStrategy" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardMapResponse) Reset() {
	*x = GetShardMapResponse{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardMapResponse) ProtoMessage() {}

func (x *GetShardMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardMapResponse.ProtoReflect.Descriptor instead.
func (*GetShardMapResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{14}
}

func (x *GetShardMapResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetShardMapResponse) GetShards() []*ShardRouteInfo {
	if x != nil {
		return x.Shards
	}
	return nil
}

func (x *GetShardMapResponse) GetShardKeyField() string {
	if x != nil {
		return x.ShardKeyField
	}
	return ""
}

func (x *GetShardMapResponse) GetStrategy() ShardingStrategy {
	if x != nil {
		return x.Strategy
	}
	return ShardingStrategy_UNKNOWN_STRATEGY
}

type AddShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShardRequest) Reset() {
	*x = AddShardRequest{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShardRequest) ProtoMessage() {}

func (x *AddShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShardRequest.ProtoReflect.Descriptor instead.
func (*AddShardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{15}
}

func (x *AddShardRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *AddShardRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AddShardRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AddShardRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type AddShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShardResponse) Reset() {
	*x = AddShardResponse{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShardResponse) ProtoMessage() {}

func (x *AddShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShardResponse.ProtoReflect.Descriptor instead.
func (*AddShardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{16}
}

func (x *AddShardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddShardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveShardRequest) Reset() {
	*x = RemoveShardRequest{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveShardRequest) ProtoMessage() {}

func (x *RemoveShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveShardRequest.ProtoReflect.Descriptor instead.
func (*RemoveShardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveShardRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type RemoveShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveShardResponse) Reset() {
	*x = RemoveShardResponse{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveShardResponse) ProtoMessage() {}

func (x *RemoveShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveShardResponse.ProtoReflect.Descriptor instead.
func (*RemoveShardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveShardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveShardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SplitChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	SplitPoint    []byte                 `protobuf:"bytes,2,opt,name=split_point,json=splitPoint,proto3" json:"split_point,omitempty"` // Key value at which to split
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitChunkRequest) Reset() {
	*x = SplitChunkRequest{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitChunkRequest) ProtoMessage() {}

func (x *SplitChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitChunkRequest.ProtoReflect.Descriptor instead.
func (*SplitChunkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{19}
}

func (x *SplitChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *SplitChunkRequest) GetSplitPoint() []byte {
	if x != nil {
		return x.SplitPoint
	}
	return nil
}

type SplitChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LeftChunkId   string                 `protobuf:"bytes,2,opt,name=left_chunk_id,json=leftChunkId,proto3" json:"left_chunk_id,omitempty"`
	RightChunkId  string                 `protobuf:"bytes,3,opt,name=right_chunk_id,json=rightChunkId,proto3" json:"right_chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitChunkResponse) Reset() {
	*x = SplitChunkResponse{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitChunkResponse) ProtoMessage() {}

func (x *SplitChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitChunkResponse.ProtoReflect.Descriptor instead.
func (*SplitChunkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{20}
}

func (x *SplitChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SplitChunkResponse) GetLeftChunkId() string {
	if x != nil {
		return x.LeftChunkId
	}
	return ""
}

func (x *SplitChunkResponse) GetRightChunkId() string {
	if x != nil {
		return x.RightChunkId
	}
	return ""
}

type MigrateChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	FromShard     string                 `protobuf:"bytes,2,opt,name=from_shard,json=fromShard,proto3" json:"from_shard,omitempty"`
	ToShard       string                 `protobuf:"bytes,3,opt,name=to_shard,json=toShard,proto3" json:"to_shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateChunkRequest) Reset() {
	*x = MigrateChunkRequest{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateChunkRequest) ProtoMessage() {}

func (x *MigrateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateChunkRequest.ProtoReflect.Descriptor instead.
func (*MigrateChunkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{21}
}

func (x *MigrateChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *MigrateChunkRequest) GetFromShard() string {
	if x != nil {
		return x.FromShard
	}
	return ""
}

func (x *MigrateChunkRequest) GetToShard() string {
	if x != nil {
		return x.ToShard
	}
	return ""
}

type MigrateChunkResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DocumentsMigrated int64                  `protobuf:"varint,2,opt,name=documents_migrated,json=documentsMigrated,proto3" json:"documents_migrated,omitempty"`
	Error             string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MigrateChunkResponse) Reset() {
	*x = MigrateChunkResponse{}
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateChunkResponse) ProtoMessage() {}

func (x *MigrateChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_routing_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateChunkResponse.ProtoReflect.Descriptor instead.
func (*MigrateChunkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_routing_proto_rawDescGZIP(), []int{22}
}

func (x *MigrateChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MigrateChunkResponse) GetDocumentsMigrated() int64 {
	if x != nil {
		return x.DocumentsMigrated
	}
	return 0
}

func (x *MigrateChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_cluster_proto_routing_proto protoreflect.FileDescriptor

const file_pkg_cluster_proto_routing_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/cluster/proto/routing.proto\x12\x0flauradb.cluster\x1a\x1epkg/cluster/proto/common.proto\"\xfa\x01\n" +
	"\fQueryRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x14\n" +
	"\x05query\x18\x04 \x01(\fR\x05query\x12\x1e\n" +
	"\n" +
	"projection\x18\x05 \x01(\fR\n" +
	"projection\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04skip\x18\a \x01(\x03R\x04skip\x12\x12\n" +
	"\x04sort\x18\b \x01(\fR\x04sort\x12\x1b\n" +
	"\tshard_key\x18\t \x01(\fR\bshardKey\"\xc3\x01\n" +
	"\rQueryResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\tdocuments\x18\x02 \x03(\fR\tdocuments\x12%\n" +
	"\x0emore_available\x18\x03 \x01(\bR\rmoreAvailable\x12\x1b\n" +
	"\tcursor_id\x18\x04 \x01(\tR\bcursorId\x121\n" +
	"\x05stats\x18\x05 \x01(\v2\x1b.lauradb.cluster.QueryStatsR\x05stats\"\xbd\x01\n" +
	"\n" +
	"QueryStats\x12-\n" +
	"\x12documents_examined\x18\x01 \x01(\x05R\x11documentsExamined\x12-\n" +
	"\x12documents_returned\x18\x02 \x01(\x05R\x11documentsReturned\x12*\n" +
	"\x11execution_time_ms\x18\x03 \x01(\x03R\x0fexecutionTimeMs\x12%\n" +
	"\x0eshards_queried\x18\x04 \x03(\tR\rshardsQueried\"\xa2\x01\n" +
	"\rInsertRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x1c\n" +
	"\tdocuments\x18\x04 \x03(\fR\tdocuments\x12\x18\n" +
	"\aordered\x18\x05 \x01(\bR\aordered\"\x8c\x01\n" +
	"\x0eInsertResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0einserted_count\x18\x02 \x01(\x05R\rinsertedCount\x124\n" +
	"\x06errors\x18\x03 \x03(\v2\x1c.lauradb.cluster.InsertErrorR\x06errors\"9\n" +
	"\vInsertError\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc6\x01\n" +
	"\rUpdateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x14\n" +
	"\x05query\x18\x04 \x01(\fR\x05query\x12\x16\n" +
	"\x06update\x18\x05 \x01(\fR\x06update\x12\x14\n" +
	"\x05multi\x18\x06 \x01(\bR\x05multi\x12\x16\n" +
	"\x06upsert\x18\a \x01(\bR\x06upsert\"\xa2\x01\n" +
	"\x0eUpdateResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rmatched_count\x18\x02 \x01(\x05R\fmatchedCount\x12%\n" +
	"\x0emodified_count\x18\x03 \x01(\x05R\rmodifiedCount\x12%\n" +
	"\x0eupserted_count\x18\x04 \x01(\x05R\rupsertedCount\"\x96\x01\n" +
	"\rDeleteRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x14\n" +
	"\x05query\x18\x04 \x01(\fR\x05query\x12\x14\n" +
	"\x05multi\x18\x05 \x01(\bR\x05multi\"T\n" +
	"\x0eDeleteResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x05R\fdeletedCount\"\x8b\x01\n" +
	"\x12AggregationRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x1a\n" +
	"\bpipeline\x18\x04 \x03(\fR\bpipeline\"N\n" +
	"\x13AggregationResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\aresults\x18\x02 \x03(\fR\aresults\"\xa1\x01\n" +
	"\x0eShardRouteInfo\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x123\n" +
	"\x06chunks\x18\x05 \x03(\v2\x1b.lauradb.cluster.ChunkRangeR\x06chunks\"j\n" +
	"\x12GetShardMapRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\xcf\x01\n" +
	"\x13GetShardMapResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x127\n" +
	"\x06shards\x18\x02 \x03(\v2\x1f.lauradb.cluster.ShardRouteInfoR\x06shards\x12&\n" +
	"\x0fshard_key_field\x18\x03 \x01(\tR\rshardKeyField\x12=\n" +
	"\bstrategy\x18\x04 \x01(\x0e2!.lauradb.cluster.ShardingStrategyR\bstrategy\"m\n" +
	"\x0fAddShardRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\"F\n" +
	"\x10AddShardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x12RemoveShardRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"I\n" +
	"\x13RemoveShardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x11SplitChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1f\n" +
	"\vsplit_point\x18\x02 \x01(\fR\n" +
	"splitPoint\"x\n" +
	"\x12SplitChunkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\rleft_chunk_id\x18\x02 \x01(\tR\vleftChunkId\x12$\n" +
	"\x0eright_chunk_id\x18\x03 \x01(\tR\frightChunkId\"j\n" +
	"\x13MigrateChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1d\n" +
	"\n" +
	"from_shard\x18\x02 \x01(\tR\tfromShard\x12\x19\n" +
	"\bto_shard\x18\x03 \x01(\tR\atoShard\"u\n" +
	"\x14MigrateChunkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\x12documents_migrated\x18\x02 \x01(\x03R\x11documentsMigrated\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*K\n" +
	"\x10ShardingStrategy\x12\x14\n" +
	"\x10UNKNOWN_STRATEGY\x10\x00\x12\b\n" +
	"\x04HASH\x10\x01\x12\t\n" +
	"\x05RANGE\x10\x02\x12\f\n" +
	"\bCOMPOUND\x10\x032\xea\x03\n" +
	"\rRouterService\x12F\n" +
	"\x05Query\x12\x1d.lauradb.cluster.QueryRequest\x1a\x1e.lauradb.cluster.QueryResponse\x12I\n" +
	"\x06Insert\x12\x1e.lauradb.cluster.InsertRequest\x1a\x1f.lauradb.cluster.InsertResponse\x12I\n" +
	"\x06Update\x12\x1e.lauradb.cluster.UpdateRequest\x1a\x1f.lauradb.cluster.UpdateResponse\x12I\n" +
	"\x06Delete\x12\x1e.lauradb.cluster.DeleteRequest\x1a\x1f.lauradb.cluster.DeleteResponse\x12V\n" +
	"\tAggregate\x12#.lauradb.cluster.AggregationRequest\x1a$.lauradb.cluster.AggregationResponse\x12X\n" +
	"\vGetShardMap\x12#.lauradb.cluster.GetShardMapRequest\x1a$.lauradb.cluster.GetShardMapResponse2\xee\x02\n" +
	"\rConfigService\x12O\n" +
	"\bAddShard\x12 .lauradb.cluster.AddShardRequest\x1a!.lauradb.cluster.AddShardResponse\x12X\n" +
	"\vRemoveShard\x12#.lauradb.cluster.RemoveShardRequest\x1a$.lauradb.cluster.RemoveShardResponse\x12U\n" +
	"\n" +
	"SplitChunk\x12\".lauradb.cluster.SplitChunkRequest\x1a#.lauradb.cluster.SplitChunkResponse\x12[\n" +
	"\fMigrateChunk\x12$.lauradb.cluster.MigrateChunkRequest\x1a%.lauradb.cluster.MigrateChunkResponseB1Z/github.com/mnohosten/laura-db/pkg/cluster/protob\x06proto3"

var (
	file_pkg_cluster_proto_routing_proto_rawDescOnce sync.Once
	file_pkg_cluster_proto_routing_proto_rawDescData []byte
)

func file_pkg_cluster_proto_routing_proto_rawDescGZIP() []byte {
	file_pkg_cluster_proto_routing_proto_rawDescOnce.Do(func() {
		file_pkg_cluster_proto_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_cluster_proto_routing_proto_rawDesc), len(file_pkg_cluster_proto_routing_proto_rawDesc)))
	})
	return file_pkg_cluster_proto_routing_proto_rawDescData
}

var file_pkg_cluster_proto_routing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_cluster_proto_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkg_cluster_proto_routing_proto_goTypes = []any{
	(ShardingStrategy)(0),        // 0: lauradb.cluster.ShardingStrategy
	(*QueryRequest)(nil),         // 1: lauradb.cluster.QueryRequest
	(*QueryResponse)(nil),        // 2: lauradb.cluster.QueryResponse
	(*QueryStats)(nil),           // 3: lauradb.cluster.QueryStats
	(*InsertRequest)(nil),        // 4: lauradb.cluster.InsertRequest
	(*InsertResponse)(nil),       // 5: lauradb.cluster.InsertResponse
	(*InsertError)(nil),          // 6: lauradb.cluster.InsertError
	(*UpdateRequest)(nil),        // 7: lauradb.cluster.UpdateRequest
	(*UpdateResponse)(nil),       // 8: lauradb.cluster.UpdateResponse
	(*DeleteRequest)(nil),        // 9: lauradb.cluster.DeleteRequest
	(*DeleteResponse)(nil),       // 10: lauradb.cluster.DeleteResponse
	(*AggregationRequest)(nil),   // 11: lauradb.cluster.AggregationRequest
	(*AggregationResponse)(nil),  // 12: lauradb.cluster.AggregationResponse
	(*ShardRouteInfo)(nil),       // 13: lauradb.cluster.ShardRouteInfo
	(*GetShardMapRequest)(nil),   // 14: lauradb.cluster.GetShardMapRequest
	(*GetShardMapResponse)(nil),  // 15: lauradb.cluster.GetShardMapResponse
	(*AddShardRequest)(nil),      // 16: lauradb.cluster.AddShardRequest
	(*AddShardResponse)(nil),     // 17: lauradb.cluster.AddShardResponse
	(*RemoveShardRequest)(nil),   // 18: lauradb.cluster.RemoveShardRequest
	(*RemoveShardResponse)(nil),  // 19: lauradb.cluster.RemoveShardResponse
	(*SplitChunkRequest)(nil),    // 20: lauradb.cluster.SplitChunkRequest
	(*SplitChunkResponse)(nil),   // 21: lauradb.cluster.SplitChunkResponse
	(*MigrateChunkRequest)(nil),  // 22: lauradb.cluster.MigrateChunkRequest
	(*MigrateChunkResponse)(nil), // 23: lauradb.cluster.MigrateChunkResponse
	(*ChunkRange)(nil),           // 24: lauradb.cluster.ChunkRange
}
var file_pkg_cluster_proto_routing_proto_depIdxs = []int32{
	3,  // 0: lauradb.cluster.QueryResponse.stats:type_name -> lauradb.cluster.QueryStats
	6,  // 1: lauradb.cluster.InsertResponse.errors:type_name -> lauradb.cluster.InsertError
	24, // 2: lauradb.cluster.ShardRouteInfo.chunks:type_name -> lauradb.cluster.ChunkRange
	13, // 3: lauradb.cluster.GetShardMapResponse.shards:type_name -> lauradb.cluster.ShardRouteInfo
	0,  // 4: lauradb.cluster.GetShardMapResponse.strategy:type_name -> lauradb.cluster.ShardingStrategy
	1,  // 5: lauradb.cluster.RouterService.Query:input_type -> lauradb.cluster.QueryRequest
	4,  // 6: lauradb.cluster.RouterService.Insert:input_type -> lauradb.cluster.InsertRequest
	7,  // 7: lauradb.cluster.RouterService.Update:input_type -> lauradb.cluster.UpdateRequest
	9,  // 8: lauradb.cluster.RouterService.Delete:input_type -> lauradb.cluster.DeleteRequest
	11, // 9: lauradb.cluster.RouterService.Aggregate:input_type -> lauradb.cluster.AggregationRequest
	14, // 10: lauradb.cluster.RouterService.GetShardMap:input_type -> lauradb.cluster.GetShardMapRequest
	16, // 11: lauradb.cluster.ConfigService.AddShard:input_type -> lauradb.cluster.AddShardRequest
	18, // 12: lauradb.cluster.ConfigService.RemoveShard:input_type -> lauradb.cluster.RemoveShardRequest
	20, // 13: lauradb.cluster.ConfigService.SplitChunk:input_type -> lauradb.cluster.SplitChunkRequest
	22, // 14: lauradb.cluster.ConfigService.MigrateChunk:input_type -> lauradb.cluster.MigrateChunkRequest
	2,  // 15: lauradb.cluster.RouterService.Query:output_type -> lauradb.cluster.QueryResponse
	5,  // 16: lauradb.cluster.RouterService.Insert:output_type -> lauradb.cluster.InsertResponse
	8,  // 17: lauradb.cluster.RouterService.Update:output_type -> lauradb.cluster.UpdateResponse
	10, // 18: lauradb.cluster.RouterService.Delete:output_type -> lauradb.cluster.DeleteResponse
	12, // 19: lauradb.cluster.RouterService.Aggregate:output_type -> lauradb.cluster.AggregationResponse
	15, // 20: lauradb.cluster.RouterService.GetShardMap:output_type -> lauradb.cluster.GetShardMapResponse
	17, // 21: lauradb.cluster.ConfigService.AddShard:output_type -> lauradb.cluster.AddShardResponse
	19, // 22: lauradb.cluster.ConfigService.RemoveShard:output_type -> lauradb.cluster.RemoveShardResponse
	21, // 23: lauradb.cluster.ConfigService.SplitChunk:output_type -> lauradb.cluster.SplitChunkResponse
	23, // 24: lauradb.cluster.ConfigService.MigrateChunk:output_type -> lauradb.cluster.MigrateChunkResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_cluster_proto_routing_proto_init() }
func file_pkg_cluster_proto_routing_proto_init() {
	if File_pkg_cluster_proto_routing_proto != nil {
		return
	}
	file_pkg_cluster_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_cluster_proto_routing_proto_rawDesc), len(file_pkg_cluster_proto_routing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_cluster_proto_routing_proto_goTypes,
		DependencyIndexes: file_pkg_cluster_proto_routing_proto_depIdxs,
		EnumInfos:         file_pkg_cluster_proto_routing_proto_enumTypes,
		MessageInfos:      file_pkg_cluster_proto_routing_proto_msgTypes,
	}.Build()
	File_pkg_cluster_proto_routing_proto = out.File
	file_pkg_cluster_proto_routing_proto_goTypes = nil
	file_pkg_cluster_proto_routing_proto_depIdxs = nil
}
