// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/cluster/proto/transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionState int32

const (
	TransactionState_UNKNOWN_STATE TransactionState = 0
	TransactionState_ACTIVE        TransactionState = 1
	TransactionState_PREPARING     TransactionState = 2
	TransactionState_PREPARED      TransactionState = 3
	TransactionState_COMMITTING    TransactionState = 4
	TransactionState_COMMITTED     TransactionState = 5
	TransactionState_ABORTING      TransactionState = 6
	TransactionState_ABORTED       TransactionState = 7
)

// Enum value maps for TransactionState.
var (
	TransactionState_name = map[int32]string{
		0: "UNKNOWN_STATE",
		1: "ACTIVE",
		2: "PREPARING",
		3: "PREPARED",
		4: "COMMITTING",
		5: "COMMITTED",
		6: "ABORTING",
		7: "ABORTED",
	}
	TransactionState_value = map[string]int32{
		"UNKNOWN_STATE": 0,
		"ACTIVE":        1,
		"PREPARING":     2,
		"PREPARED":      3,
		"COMMITTING":    4,
		"COMMITTED":     5,
		"ABORTING":      6,
		"ABORTED":       7,
	}
)

func (x TransactionState) Enum() *TransactionState {
	p := new(TransactionState)
	*p = x
	return p
}

func (x TransactionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_cluster_proto_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionState) Type() protoreflect.EnumType {
	return &file_pkg_cluster_proto_transaction_proto_enumTypes[0]
}

func (x TransactionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionState.Descriptor instead.
func (TransactionState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_transaction_proto_rawDescGZIP(), []int{0}
}

// Transaction represents a distributed transaction
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`  // Unique transaction identifier
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`      // Transaction start time
	Participants  []string               `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"` // Node IDs participating
	State         TransactionState       `protobuf:"varint,4,opt,name=state,proto3,enum=lauradb.cluster.TransactionState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *Transaction) GetState() TransactionState {
	if x != nil {
		return x.State
	}
	return TransactionState_UNKNOWN_STATE
}

// Phase 1: Prepare
type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	CoordinatorId string                 `protobuf:"bytes,2,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	Operations    []*Operation           `protobuf:"bytes,3,rep,name=operations,proto3" json:"operations,omitempty"` // Operations to prepare
	TimeoutMs     int64                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *PrepareRequest) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

func (x *PrepareRequest) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *PrepareRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	OpType        OperationType          `protobuf:"varint,3,opt,name=op_type,json=opType,proto3,enum=lauradb.cluster.OperationType" json:"op_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // Serialized operation data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *Operation) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Operation) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Operation) GetOpType() OperationType {
	if x != nil {
		return x.OpType
	}
	return OperationType_UNKNOWN_OP
}

func (x *Operation) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PrepareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Vote          bool                   `protobuf:"varint,3,opt,name=vote,proto3" json:"vote,omitempty"` // true = prepared, false = abort
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareResponse) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *PrepareResponse) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *PrepareResponse) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

func (x *PrepareResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Phase 2: Commit or Abort
type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	CoordinatorId string                 `protobuf:"bytes,2,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *CommitRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *CommitRequest) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *CommitResponse) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *CommitResponse) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *CommitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	CoordinatorId string                 `protobuf:"bytes,2,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *AbortRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *AbortRequest) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

func (x *AbortRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AbortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortResponse) Reset() {
	*x = AbortResponse{}
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortResponse) ProtoMessage() {}

func (x *AbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortResponse.ProtoReflect.Descriptor instead.
func (*AbortResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *AbortResponse) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *AbortResponse) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *AbortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AbortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Transaction recovery for failed coordinator
type RecoveryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TxnId            string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	RequestingNodeId string                 `protobuf:"bytes,2,opt,name=requesting_node_id,json=requestingNodeId,proto3" json:"requesting_node_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecoveryRequest) Reset() {
	*x = RecoveryRequest{}
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryRequest) ProtoMessage() {}

func (x *RecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryRequest.ProtoReflect.Descriptor instead.
func (*RecoveryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *RecoveryRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *RecoveryRequest) GetRequestingNodeId() string {
	if x != nil {
		return x.RequestingNodeId
	}
	return ""
}

type RecoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	State         TransactionState       `protobuf:"varint,2,opt,name=state,proto3,enum=lauradb.cluster.TransactionState" json:"state,omitempty"`
	Participants  []string               `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"`
	CoordinatorId string                 `protobuf:"bytes,4,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryResponse) Reset() {
	*x = RecoveryResponse{}
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryResponse) ProtoMessage() {}

func (x *RecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_proto_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryResponse.ProtoReflect.Descriptor instead.
func (*RecoveryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_proto_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *RecoveryResponse) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *RecoveryResponse) GetState() TransactionState {
	if x != nil {
		return x.State
	}
	return TransactionState_UNKNOWN_STATE
}

func (x *RecoveryResponse) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *RecoveryResponse) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

var File_pkg_cluster_proto_transaction_proto protoreflect.FileDescriptor

const file_pkg_cluster_proto_transaction_proto_rawDesc = "" +
	"\n" +
	"#pkg/cluster/proto/transaction.proto\x12\x0flauradb.cluster\x1a\x1epkg/cluster/proto/common.proto\"\x9f\x01\n" +
	"\vTransaction\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\"\n" +
	"\fparticipants\x18\x03 \x03(\tR\fparticipants\x127\n" +
	"\x05state\x18\x04 \x01(\x0e2!.lauradb.cluster.TransactionStateR\x05state\"\xa9\x01\n" +
	"\x0ePrepareRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12%\n" +
	"\x0ecoordinator_id\x18\x02 \x01(\tR\rcoordinatorId\x12:\n" +
	"\n" +
	"operations\x18\x03 \x03(\v2\x1a.lauradb.cluster.OperationR\n" +
	"operations\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x03R\ttimeoutMs\"\x94\x01\n" +
	"\tOperation\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x127\n" +
	"\aop_type\x18\x03 \x01(\x0e2\x1e.lauradb.cluster.OperationTypeR\x06opType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"y\n" +
	"\x0fPrepareResponse\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\x12\n" +
	"\x04vote\x18\x03 \x01(\bR\x04vote\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"M\n" +
	"\rCommitRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12%\n" +
	"\x0ecoordinator_id\x18\x02 \x01(\tR\rcoordinatorId\"~\n" +
	"\x0eCommitResponse\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"d\n" +
	"\fAbortRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12%\n" +
	"\x0ecoordinator_id\x18\x02 \x01(\tR\rcoordinatorId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"}\n" +
	"\rAbortResponse\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"V\n" +
	"\x0fRecoveryRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12,\n" +
	"\x12requesting_node_id\x18\x02 \x01(\tR\x10requestingNodeId\"\xad\x01\n" +
	"\x10RecoveryResponse\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x127\n" +
	"\x05state\x18\x02 \x01(\x0e2!.lauradb.cluster.TransactionStateR\x05state\x12\"\n" +
	"\fparticipants\x18\x03 \x03(\tR\fparticipants\x12%\n" +
	"\x0ecoordinator_id\x18\x04 \x01(\tR\rcoordinatorId*\x88\x01\n" +
	"\x10TransactionState\x12\x11\n" +
	"\rUNKNOWN_STATE\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\r\n" +
	"\tPREPARING\x10\x02\x12\f\n" +
	"\bPREPARED\x10\x03\x12\x0e\n" +
	"\n" +
	"COMMITTING\x10\x04\x12\r\n" +
	"\tCOMMITTED\x10\x05\x12\f\n" +
	"\bABORTING\x10\x06\x12\v\n" +
	"\aABORTED\x10\a2\xd3\x02\n" +
	"\x12TransactionService\x12L\n" +
	"\aPrepare\x12\x1f.lauradb.cluster.PrepareRequest\x1a .lauradb.cluster.PrepareResponse\x12I\n" +
	"\x06Commit\x12\x1e.lauradb.cluster.CommitRequest\x1a\x1f.lauradb.cluster.CommitResponse\x12F\n" +
	"\x05Abort\x12\x1d.lauradb.cluster.AbortRequest\x1a\x1e.lauradb.cluster.AbortResponse\x12\\\n" +
	"\x15QueryTransactionState\x12 .lauradb.cluster.RecoveryRequest\x1a!.lauradb.cluster.RecoveryResponseB1Z/github.com/mnohosten/laura-db/pkg/cluster/protob\x06proto3"

var (
	file_pkg_cluster_proto_transaction_proto_rawDescOnce sync.Once
	file_pkg_cluster_proto_transaction_proto_rawDescData []byte
)

func file_pkg_cluster_proto_transaction_proto_rawDescGZIP() []byte {
	file_pkg_cluster_proto_transaction_proto_rawDescOnce.Do(func() {
		file_pkg_cluster_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_cluster_proto_transaction_proto_rawDesc), len(file_pkg_cluster_proto_transaction_proto_rawDesc)))
	})
	return file_pkg_cluster_proto_transaction_proto_rawDescData
}

var file_pkg_cluster_proto_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_cluster_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_cluster_proto_transaction_proto_goTypes = []any{
	(TransactionState)(0),    // 0: lauradb.cluster.TransactionState
	(*Transaction)(nil),      // 1: lauradb.cluster.Transaction
	(*PrepareRequest)(nil),   // 2: lauradb.cluster.PrepareRequest
	(*Operation)(nil),        // 3: lauradb.cluster.Operation
	(*PrepareResponse)(nil),  // 4: lauradb.cluster.PrepareResponse
	(*CommitRequest)(nil),    // 5: lauradb.cluster.CommitRequest
	(*CommitResponse)(nil),   // 6: lauradb.cluster.CommitResponse
	(*AbortRequest)(nil),     // 7: lauradb.cluster.AbortRequest
	(*AbortResponse)(nil),    // 8: lauradb.cluster.AbortResponse
	(*RecoveryRequest)(nil),  // 9: lauradb.cluster.RecoveryRequest
	(*RecoveryResponse)(nil), // 10: lauradb.cluster.RecoveryResponse
	(OperationType)(0),       // 11: lauradb.cluster.OperationType
}
var file_pkg_cluster_proto_transaction_proto_depIdxs = []int32{
	0,  // 0: lauradb.cluster.Transaction.state:type_name -> lauradb.cluster.TransactionState
	3,  // 1: lauradb.cluster.PrepareRequest.operations:type_name -> lauradb.cluster.Operation
	11, // 2: lauradb.cluster.Operation.op_type:type_name -> lauradb.cluster.OperationType
	0,  // 3: lauradb.cluster.RecoveryResponse.state:type_name -> lauradb.cluster.TransactionState
	2,  // 4: lauradb.cluster.TransactionService.Prepare:input_type -> lauradb.cluster.PrepareRequest
	5,  // 5: lauradb.cluster.TransactionService.Commit:input_type -> lauradb.cluster.CommitRequest
	7,  // 6: lauradb.cluster.TransactionService.Abort:input_type -> lauradb.cluster.AbortRequest
	9,  // 7: lauradb.cluster.TransactionService.QueryTransactionState:input_type -> lauradb.cluster.RecoveryRequest
	4,  // 8: lauradb.cluster.TransactionService.Prepare:output_type -> lauradb.cluster.PrepareResponse
	6,  // 9: lauradb.cluster.TransactionService.Commit:output_type -> lauradb.cluster.CommitResponse
	8,  // 10: lauradb.cluster.TransactionService.Abort:output_type -> lauradb.cluster.AbortResponse
	10, // 11: lauradb.cluster.TransactionService.QueryTransactionState:output_type -> lauradb.cluster.RecoveryResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_cluster_proto_transaction_proto_init() }
func file_pkg_cluster_proto_transaction_proto_init() {
	if File_pkg_cluster_proto_transaction_proto != nil {
		return
	}
	file_pkg_cluster_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_cluster_proto_transaction_proto_rawDesc), len(file_pkg_cluster_proto_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_cluster_proto_transaction_proto_goTypes,
		DependencyIndexes: file_pkg_cluster_proto_transaction_proto_depIdxs,
		EnumInfos:         file_pkg_cluster_proto_transaction_proto_enumTypes,
		MessageInfos:      file_pkg_cluster_proto_transaction_proto_msgTypes,
	}.Build()
	File_pkg_cluster_proto_transaction_proto = out.File
	file_pkg_cluster_proto_transaction_proto_goTypes = nil
	file_pkg_cluster_proto_transaction_proto_depIdxs = nil
}
